# Generated by Django 3.2.5 on 2021-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_bot',
            name='email_password',
            field=models.CharField(default='Default_password', max_length=40),
        ),
    ]
